### ISSUE TITLE
EnrollServlet call fails after when grid is up

### ISSUE THREAD

**Issue by bharathc02** [RationaleEmotions/just-ask#10]
Selenium Stand alone server : 3.7.1
Just-ask : 1.0.3

I've started the selenium grid using the command below,
`java -Dconfig.file=config.json -cp selenium-server-standalone-3.7.1.jar:just-ask-1.0.3-jar-with-dependencies.jar org.openqa.grid.selenium.GridLauncherV3 -role hub -servlets com.rationaleemotions.servlets.EnrollServlet`

Selenium Grid hub starts successfully.
When wiring in the Ghost Proxy into the hub via URL http://localhost:4444/grid/admin/EnrollServlet, it throws `java.lang.IllegalStateException: There was a problem in hooking in the ghost node.`.
[Entire exception grid.txt](https://github.com/RationaleEmotions/just-ask/files/1501278/grid.txt)

Upon reviewing the code, I noticed that Selenium has deprecated the Registry class ([link](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/Registry.java)). 

Just-ask is using Registry class in [GhostProxy](https://github.com/RationaleEmotions/just-ask/blob/master/src/main/java/com/rationaleemotions/proxy/GhostProxy.java#L45) and [EnrollServlet](https://github.com/RationaleEmotions/just-ask/blob/master/src/main/java/com/rationaleemotions/servlets/EnrollServlet.java#L37).

To fix this, both these classes must resort to using the interface [GridRegistry](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/GridRegistry.java) instead of [Registry](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/Registry.java)

**Comment by krmahadevan** [comment]
Fixed by https://github.com/RationaleEmotions/just-ask/pull/11
