### ISSUE TITLE
Allow to pass environmental variables to docker container

### ISSUE THREAD

**Issue by Gytiss** [RationaleEmotions/just-ask#14]
It would be nice to be able to pass environmental variables to Selenium container. One example being to mount a drives for file sharing. 
From what I understand spotify allows that. They have an opened issue here:
https://github.com/spotify/docker-client/issues/897
Again, unclear how to pass those. My best guess is json configuration file would be a good target.

**Comment by krmahadevan** [comment]
Fixed as part of https://github.com/RationaleEmotions/just-ask/pull/17
