### ISSUE TITLE
Allow to pull images from internal repository

### ISSUE THREAD

**Issue by Gytiss** [RationaleEmotions/just-ask#15]
Currently the only way to pull images is from public docker HUB. If company is using it's own repository and does not allow to pull images from public HUB repo, this solution cannot be used.
I see that you can create an object with custom server configuration like that:
`RegistryAuth auth = RegistryAuth.builder().password("test").serverAddress("test").username("test").build();` and pass it DockerClient pull method.
Somehow those parameters would need to be passed though, maybe via command line arguments as it would contain user password.

**Comment by krmahadevan** [comment]
@Gytiss - Are you looking at addressing this issue also before we do a quick release for your usage ?

**Comment by Gytiss** [comment]
@krmahadevan, no I am not currently doing anything with this. Feel free to release new version :)

**Comment by Gytiss** [comment]
@krmahadevan 
This can be actually solved by passing remote repository name in front of docker image name in config.json, like:
**YourRepoName**/selenium/standalone-firefox-debug:latest
This can be closed now.
