### ISSUE TITLE
Container shutdown in afterSession

### ISSUE THREAD

**Issue by Gytiss** [RationaleEmotions/just-ask#21]
Consider container shutdown in `afterSession()` instead of `afterCommand()`.
There are a few reasons for that. The main one is that sometimes you can pass correct **alwaysMatch** capability and session will be created, but it will be cancelled due to some wrong other capabilities, ie platformName sent as empty string. In this scenario container is left running and not closed.
Also, I believe it should be faster to close session in `afterSession()`, as there would be no need to check every command in `afterCommand()` method. Tested this change and I see containers closing correctly.
I can open a PR for this change.

**Comment by krmahadevan** [comment]
@Gytiss - I can't remember why I chose specifically to have the container shutdown done via an `afterCommand()` instead of relying on `afterSession()`. I will update here if I can remember it. But yeah you can open up a PR for this.

**Comment by krmahadevan** [comment]
Closed via https://github.com/RationaleEmotions/just-ask/pull/24
