### ISSUE TITLE
Add ability to mount drives

### ISSUE THREAD

**Issue by Gytiss** [RationaleEmotions/just-ask#23]
This would not only be a new feature, but there a times when docker node simply crashes seemingly without any reason, but I found that it is a known issue due tue containers not started with mount option: https://github.com/SeleniumHQ/docker-selenium/issues/392
As a workaround user can send `--disable-dev-shm-usage` capability to prevent random container crashes

**Comment by krmahadevan** [comment]
Closed via https://github.com/RationaleEmotions/just-ask/pull/26
